### ISSUE TITLE
Found error causing tab switching to freeze 

### ISSUE THREAD

**Issue by MichalKononenko** [OmicronProject/BakeoutController-Basic#18]
```
17:48:57.635 [pool-2-thread-2] DEBUG ui.controllers.ResultController$ChangeHandler - Controller for variable Pressure received change event for variable kernel.models.variables.PressureDataPoint@2ea86df5
Exception in thread "pool-2-thread-2" java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-2
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
	at javafx.scene.chart.LineChart.dataItemAdded(LineChart.java:291)
	at javafx.scene.chart.XYChart.dataItemsChanged(XYChart.java:501)
	at javafx.scene.chart.XYChart.access$2300(XYChart.java:93)
	at javafx.scene.chart.XYChart$Series$1.onChanged(XYChart.java:1488)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at ui.controllers.ResultController$ChangeHandler.updateChart(ResultController.java:184)
	at ui.controllers.ResultController$ChangeHandler.onChange(ResultController.java:155)
	at kernel.models.variables.PressureProvider$PressurePollingTask.updateListeners(PressureProvider.java:143)
	at kernel.models.variables.PressureProvider$PressurePollingTask.run(PressureProvider.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-2" java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-2
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
	at javafx.scene.chart.LineChart.dataItemRemoved(LineChart.java:366)
	at javafx.scene.chart.XYChart.dataItemsChanged(XYChart.java:497)
	at javafx.scene.chart.XYChart.access$2300(XYChart.java:93)
	at javafx.scene.chart.XYChart$Series$1.onChanged(XYChart.java:1488)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	at ui.controllers.ResultController$ChangeHandler.checkSizeListCorrect(ResultController.java:195)
	at ui.controllers.ResultController$ChangeHandler.updateChart(ResultController.java:188)
	at ui.controllers.ResultController$ChangeHandler.onChange(ResultController.java:155)
	at kernel.models.variables.PressureProvider$PressurePollingTask.updateListeners(PressureProvider.java:143)
	at kernel.models.variables.PressureProvider$PressurePollingTask.run(PressureProvider.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MichalKononenko** [comment]
This has been fixed
